import { DbOperationFunction } from "@workspace/canvas/types";

function toPascal(str: string): string {
  const clean = (str || "table").trim().replace(/[^a-zA-Z0-9_\-\s]/g, "");
  if (!clean) return "Table";
  return clean
    .split(/[_\-\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function toCamel(str: string): string {
  const p = toPascal(str);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

/**
 * Generates default auto-created database operation functions for an entity table,
 * including standard CRUD and index-based fetch functions (fetchByIndex).
 * Populates both natural language prompts and executable TypeScript query code.
 */
export function generateDefaultDbOperations(
  label: string,
  columns: { name: string; type: string; isPrimaryKey?: boolean; isUnique?: boolean }[] = [],
  indexes: { name: string; columns: string; isUnique?: boolean }[] = [],
): DbOperationFunction[] {
  const tableName = label || "table";
  const pascal = toPascal(tableName);
  const pkCol = columns.find((c) => c.isPrimaryKey) || columns[0];
  const pkName = pkCol?.name || "id";
  const pkType =
    (pkCol?.type || "string").toLowerCase() === "number" ||
    (pkCol?.type || "string").toLowerCase() === "integer"
      ? "number"
      : "string";

  const ops: DbOperationFunction[] = [
    {
      id: `auto-find-all-${tableName}`,
      name: `findAll${pascal}`,
      kind: "findAll",
      description: `Retrieve all rows from ${tableName}`,
      signature: `findAll${pascal}(limit?: number, offset?: number): ${pascal}Row[]`,
      params: [
        { name: "limit", type: "number", required: false, defaultValue: "20" },
        { name: "offset", type: "number", required: false, defaultValue: "0" },
      ],
      returnType: `${pascal}Row[]`,
      pagination: {
        enabled: true,
        defaultLimit: 20,
        maxLimit: 100,
        mode: "offset",
      },
      logicMode: "natural_language",
      prompt: `Retrieve all records from the ${tableName} table using prepared statements with limit and offset pagination.`,
      code: `export function findAll${pascal}(limit: number = 20, offset: number = 0): ${pascal}Row[] {\n  return db.prepare("SELECT * FROM ${tableName} LIMIT ? OFFSET ?").all(limit, offset) as ${pascal}Row[];\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `auto-find-by-id-${tableName}`,
      name: `find${pascal}ById`,
      kind: "findById",
      description: `Find a ${tableName} record by ${pkName}`,
      signature: `find${pascal}ById(${pkName}: ${pkType}): ${pascal}Row | undefined`,
      params: [{ name: pkName, type: pkType, required: true }],
      returnType: `${pascal}Row | undefined`,
      logicMode: "natural_language",
      prompt: `Find a single record from the ${tableName} table by primary key (${pkName}). Returns undefined if not found.`,
      code: `export function find${pascal}ById(${pkName}: ${pkType}): ${pascal}Row | undefined {\n  return db.prepare("SELECT * FROM ${tableName} WHERE ${pkName} = ?").get(${pkName}) as ${pascal}Row | undefined;\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `auto-create-${tableName}`,
      name: `create${pascal}`,
      kind: "create",
      description: `Create a new record in ${tableName}`,
      signature: `create${pascal}(data: Create${pascal}Data): ${pascal}Row`,
      params: [{ name: "data", type: `Create${pascal}Data`, required: true }],
      returnType: `${pascal}Row`,
      logicMode: "natural_language",
      prompt: `Insert a new record into the ${tableName} table with provided payload fields and return the created record.`,
      code: `export function create${pascal}(data: Create${pascal}Data): ${pascal}Row {\n  const keys = Object.keys(data).join(", ");\n  const placeholders = Object.keys(data).map(() => "?").join(", ");\n  const values = Object.values(data);\n  const info = db.prepare(\`INSERT INTO ${tableName} (\${keys}) VALUES (\${placeholders})\`).run(...values);\n  return { ${pkName}: String(info.lastInsertRowid), ...data } as ${pascal}Row;\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `auto-update-${tableName}`,
      name: `update${pascal}`,
      kind: "update",
      description: `Update a ${tableName} record by ${pkName}`,
      signature: `update${pascal}(${pkName}: ${pkType}, data: Update${pascal}Data): ${pascal}Row | undefined`,
      params: [
        { name: pkName, type: pkType, required: true },
        { name: "data", type: `Update${pascal}Data`, required: true },
      ],
      returnType: `${pascal}Row | undefined`,
      logicMode: "natural_language",
      prompt: `Update an existing record in the ${tableName} table by primary key (${pkName}) with partial fields data.`,
      code: `export function update${pascal}(${pkName}: ${pkType}, data: Update${pascal}Data): ${pascal}Row | undefined {\n  const entries = Object.entries(data).filter(([_, v]) => v !== undefined);\n  if (entries.length === 0) return find${pascal}ById(${pkName});\n  const setClause = entries.map(([k]) => \`\${k} = ?\`).join(", ");\n  const values = [...entries.map(([_, v]) => v), ${pkName}];\n  db.prepare(\`UPDATE ${tableName} SET \${setClause} WHERE ${pkName} = ?\`).run(...values);\n  return find${pascal}ById(${pkName});\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `auto-delete-${tableName}`,
      name: `delete${pascal}ById`,
      kind: "delete",
      description: `Delete a ${tableName} record by ${pkName}`,
      signature: `delete${pascal}ById(${pkName}: ${pkType}): void`,
      params: [{ name: pkName, type: pkType, required: true }],
      returnType: "void",
      logicMode: "natural_language",
      prompt: `Delete a record from the ${tableName} table by primary key (${pkName}).`,
      code: `export function delete${pascal}ById(${pkName}: ${pkType}): void {\n  db.prepare("DELETE FROM ${tableName} WHERE ${pkName} = ?").run(${pkName});\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
  ];

  // Index-based fetch functions (fetchByIndex)
  indexes.forEach((idx, i) => {
    if (!idx.name && !idx.columns) return;
    const rawIdxName =
      idx.name || `idx_${idx.columns.replace(/[^a-zA-Z0-9_]/g, "_")}`;
    const pascalIdxName = toPascal(rawIdxName);
    const colList = (idx.columns || "")
      .split(",")
      .map((c) => c.trim())
      .filter(Boolean);

    const fnName = `fetchBy${pascalIdxName}`;
    const paramList: { name: string; type: string; required?: boolean; defaultValue?: string }[] = colList.map((colName) => {
      const colObj = columns.find((c) => c.name === colName);
      const colType =
        (colObj?.type || "string").toLowerCase() === "number" ? "number" : "string";
      return { name: toCamel(colName), type: colType, required: true };
    });

    if (!idx.isUnique) {
      paramList.push(
        { name: "limit", type: "number", required: false, defaultValue: "20" },
        { name: "offset", type: "number", required: false, defaultValue: "0" },
      );
    }

    const paramSig = paramList.map((p) => `${p.name}: ${p.type}`).join(", ");
    const returnType = idx.isUnique ? `${pascal}Row | undefined` : `${pascal}Row[]`;
    const whereClause = colList.map((c) => `${c} = ?`).join(" AND ");
    const fetchMethod = idx.isUnique ? "get" : "all";
    const argList = colList.map((c) => toCamel(c)).join(", ") + (idx.isUnique ? "" : ", limit, offset");

    ops.push({
      id: `auto-index-${tableName}-${rawIdxName}-${i}`,
      name: fnName,
      kind: "fetchByIndex",
      indexName: rawIdxName,
      description: `Fetch ${tableName} using index ${rawIdxName} (${colList.join(", ")})`,
      signature: `${fnName}(${paramSig}): ${returnType}`,
      params: paramList,
      returnType: returnType,
      pagination: idx.isUnique
        ? undefined
        : {
            enabled: true,
            defaultLimit: 20,
            maxLimit: 100,
            mode: "offset",
          },
      logicMode: "natural_language",
      prompt: `Fetch records from the ${tableName} table using index ${rawIdxName} matching (${colList.join(", ")}).`,
      code: idx.isUnique
        ? `export function ${fnName}(${paramSig}): ${returnType} {\n  return db.prepare("SELECT * FROM ${tableName} WHERE ${whereClause}").get(${argList}) as ${returnType};\n}`
        : `export function ${fnName}(${paramSig}): ${returnType} {\n  return db.prepare("SELECT * FROM ${tableName} WHERE ${whereClause} LIMIT ? OFFSET ?").all(${argList}) as ${returnType};\n}`,
      enabled: true,
      isAutoGenerated: true,
    });
  });

  return ops;
}
