import { DbOperationFunction } from "@workspace/canvas/types";
import { toSqlIdentifier } from "@/lib/compiler/utils";

function toPascal(str: string): string {
  const clean = toSqlIdentifier(str, "table");
  return clean
    .split(/[_\-\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function toCamel(str: string): string {
  const p = toPascal(str);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

/**
 * Generates default auto-created database operation functions for an entity table,
 * including standard CRUD and index-based fetch functions (fetchByIndex).
 * Populates both natural language prompts and executable TypeScript query code.
 */
export function generateDefaultDbOperations(
  label: string,
  rawColumns: { name: string; type: string; isPrimaryKey?: boolean; isUnique?: boolean; isForeignKey?: boolean }[] = [],
  indexes: { name: string; columns: string; isUnique?: boolean }[] = [],
): DbOperationFunction[] {
  const tableName = toSqlIdentifier(label || "table", "table");
  const pascal = toPascal(tableName);

  // Sanitize all column names against SQL identifier injections
  const columns = rawColumns.map((c) => ({
    ...c,
    name: toSqlIdentifier(c.name || "col", "col"),
  }));

  const pkCol = columns.find((c) => c.isPrimaryKey) || columns[0];
  const pkColName = pkCol?.name || "id";
  const pkVarName = toCamel(pkColName);
  const pkType =
    (pkCol?.type || "string").toLowerCase() === "number" ||
    (pkCol?.type || "string").toLowerCase() === "integer"
      ? "number"
      : "string";

  const writableCols = columns.filter((c) => !c.isPrimaryKey);
  const insertCols = writableCols.map((c) => c.name).join(", ");
  const insertPlaceholders = writableCols.map(() => "?").join(", ");
  const insertBindArgs = writableCols.map((c) => `data.${toCamel(c.name)}`).join(", ");

  const updateBranches = writableCols
    .map((c) => {
      const prop = toCamel(c.name);
      return `  if (data.${prop} !== undefined) {\n    updates.push("${c.name} = ?");\n    values.push(data.${prop});\n  }`;
    })
    .join("\n");

  const createCode = writableCols.length > 0
    ? `export function create${pascal}(data: Create${pascal}Data): ${pascal}Row {\n  const info = stmtInsert.run(${insertBindArgs});\n  const _rowId = typeof info.lastInsertRowid === "bigint" ? info.lastInsertRowid.toString() : String(info.lastInsertRowid);\n  return { ${pkColName}: _rowId, ...data } as ${pascal}Row;\n}`
    : `export function create${pascal}(): ${pascal}Row {\n  const info = db.prepare("INSERT INTO ${tableName} DEFAULT VALUES").run();\n  const _rowId = typeof info.lastInsertRowid === "bigint" ? info.lastInsertRowid.toString() : String(info.lastInsertRowid);\n  return { ${pkColName}: _rowId } as ${pascal}Row;\n}`;

  const updateCode = writableCols.length > 0
    ? `export function update${pascal}(${pkVarName}: ${pkType}, data: Update${pascal}Data): ${pascal}Row | undefined {\n  const current = find${pascal}ById(${pkVarName});\n  if (!current) return undefined;\n  const updated = { ...current, ...data };\n  stmtUpdate.run(${writableCols.map((c) => `updated.${toCamel(c.name)}`).join(", ")}, ${pkVarName});\n  return find${pascal}ById(${pkVarName});\n}`
    : `export function update${pascal}(${pkVarName}: ${pkType}): ${pascal}Row | undefined {\n  return find${pascal}ById(${pkVarName});\n}`;

  const ops: DbOperationFunction[] = [
    {
      id: `auto-find-all-${tableName}`,
      name: `findAll${pascal}`,
      kind: "findAll",
      description: `Retrieve all rows from ${tableName}`,
      signature: `findAll${pascal}(limit?: number, offset?: number): ${pascal}Row[]`,
      params: [
        { name: "limit", type: "number", required: false, defaultValue: "20" },
        { name: "offset", type: "number", required: false, defaultValue: "0" },
      ],
      returnType: `${pascal}Row[]`,
      pagination: {
        enabled: true,
        defaultLimit: 20,
        maxLimit: 100,
        mode: "offset",
      },
      logicMode: "natural_language",
      prompt: `Retrieve all records from the ${tableName} table using prepared statements with limit and offset pagination.`,
      code: `export function findAll${pascal}(limit: number = 20, offset: number = 0): ${pascal}Row[] {\n  return stmtFindAll.all(limit, offset) as ${pascal}Row[];\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `auto-find-by-id-${tableName}`,
      name: `find${pascal}ById`,
      kind: "findById",
      description: `Find a ${tableName} record by ${pkColName}`,
      signature: `find${pascal}ById(${pkVarName}: ${pkType}): ${pascal}Row | undefined`,
      params: [{ name: pkVarName, type: pkType, required: true }],
      returnType: `${pascal}Row | undefined`,
      logicMode: "natural_language",
      prompt: `Find a single record from the ${tableName} table by primary key (${pkColName}). Returns undefined if not found.`,
      code: `export function find${pascal}ById(${pkVarName}: ${pkType}): ${pascal}Row | undefined {\n  return stmtFindById.get(${pkVarName}) as ${pascal}Row | undefined;\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `auto-create-${tableName}`,
      name: `create${pascal}`,
      kind: "create",
      description: `Create a new record in ${tableName}`,
      signature: `create${pascal}(data: Create${pascal}Data): ${pascal}Row`,
      params: [{ name: "data", type: `Create${pascal}Data`, required: true }],
      returnType: `${pascal}Row`,
      logicMode: "natural_language",
      prompt: `Insert a new record into the ${tableName} table with provided payload fields and return the created record.`,
      code: createCode,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `auto-update-${tableName}`,
      name: `update${pascal}`,
      kind: "update",
      description: `Update a ${tableName} record by ${pkColName}`,
      signature: `update${pascal}(${pkVarName}: ${pkType}, data: Update${pascal}Data): ${pascal}Row | undefined`,
      params: [
        { name: pkVarName, type: pkType, required: true },
        { name: "data", type: `Update${pascal}Data`, required: true },
      ],
      returnType: `${pascal}Row | undefined`,
      logicMode: "natural_language",
      prompt: `Update an existing record in the ${tableName} table by primary key (${pkColName}) with partial fields data.`,
      code: updateCode,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `auto-delete-${tableName}`,
      name: `delete${pascal}ById`,
      kind: "delete",
      description: `Delete a ${tableName} record by ${pkColName}`,
      signature: `delete${pascal}ById(${pkVarName}: ${pkType}): void`,
      params: [{ name: pkVarName, type: pkType, required: true }],
      returnType: "void",
      logicMode: "natural_language",
      prompt: `Delete a record from the ${tableName} table by primary key (${pkColName}).`,
      code: `export function delete${pascal}ById(${pkVarName}: ${pkType}): void {\n  stmtDelete.run(${pkVarName});\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
  ];

  // Combine explicit indexes and auto-discovered foreign key / unique column indexes
  const effectiveIndexes: { name: string; columns: string; isUnique?: boolean }[] = [...indexes];

  columns.forEach((col) => {
    if (col.isPrimaryKey) return;
    if (col.isForeignKey || col.name.toLowerCase().endsWith("_id") || col.name.toLowerCase().endsWith("id")) {
      const exists = effectiveIndexes.some((idx) => {
        const cList = (idx.columns || "").split(",").map((c) => c.trim().toLowerCase());
        return cList.includes(col.name.toLowerCase());
      });
      if (!exists) {
        // Cardinality invariant: FK columns are always the N side of a relationship.
        // They must never be treated as unique — always generate .all() with pagination.
        effectiveIndexes.push({
          name: `idx_${tableName}_${col.name}`,
          columns: col.name,
          isUnique: false,
        });
      }
    }
  });

  // Index-based fetch functions (fetchByIndex)
  effectiveIndexes.forEach((idx, i) => {
    if (!idx.columns) return;
    const colList = idx.columns
      .split(",")
      .map((c) => toSqlIdentifier(c.trim(), ""))
      .filter(Boolean);

    if (colList.length === 0) return;

    const rawIdxName = idx.name || `idx_${colList.join("_")}`;
    const cleanName = rawIdxName.replace(new RegExp(`^idx_${tableName}_|^idx_|^by_`, "i"), "");
    const pascalIdxName = toPascal(cleanName || colList.join("_"));
    const fnName = `fetchBy${pascalIdxName}`;

    // Cardinality invariant: if the indexed column is a FK column, it is always N-cardinality
    // regardless of how the index was declared. Only truly unique constraints use .get().
    const colIsForeignKey = colList.some((c) =>
      columns.find((col) => col.name.toLowerCase() === c.toLowerCase())?.isForeignKey ||
      c.toLowerCase().endsWith("_id")
    );
    const isUnique = !!idx.isUnique && !colIsForeignKey;

    const paramList: { name: string; type: string; required?: boolean; defaultValue?: string }[] = colList.map((colName) => {
      const colObj = columns.find((c) => c.name.toLowerCase() === colName.toLowerCase());
      const colType =
        (colObj?.type || "string").toLowerCase() === "number" ||
        (colObj?.type || "string").toLowerCase() === "integer"
          ? "number"
          : "string";
      return { name: toCamel(colName), type: colType, required: true };
    });

    if (!isUnique) {
      paramList.push(
        { name: "limit", type: "number", required: false, defaultValue: "20" },
        { name: "offset", type: "number", required: false, defaultValue: "0" },
      );
    }

    const paramSig = paramList
      .map((p) => `${p.name}: ${p.type}${p.defaultValue ? ` = ${p.defaultValue}` : ""}`)
      .join(", ");
    const returnType = isUnique ? `${pascal}Row | undefined` : `${pascal}Row[]`;
    const whereClause = colList.map((c) => `${c} = ?`).join(" AND ");
    const argList = colList.map((c) => toCamel(c)).join(", ") + (isUnique ? "" : ", limit, offset");

    const paramTypes = colList.map((colName) => {
      const colObj = columns.find((c) => c.name.toLowerCase() === colName.toLowerCase());
      const colType =
        (colObj?.type || "string").toLowerCase() === "number" ||
        (colObj?.type || "string").toLowerCase() === "integer"
          ? "number"
          : "string";
      return `${toCamel(colName)}: ${colType}`;
    }).join(", ");

    const indexCode = isUnique
      ? `const stmtFindBy${pascalIdxName} = db.prepare<[${paramTypes}], ${pascal}Row>(\n  "SELECT * FROM ${tableName} WHERE ${whereClause}"\n);\n\nexport function ${fnName}(${paramSig}): ${returnType} {\n  return stmtFindBy${pascalIdxName}.get(${argList}) as ${returnType};\n}`
      : `const stmtFindBy${pascalIdxName} = db.prepare<[${paramTypes}, limit?: number, offset?: number], ${pascal}Row>(\n  "SELECT * FROM ${tableName} WHERE ${whereClause} LIMIT ? OFFSET ?"\n);\n\nexport function ${fnName}(${paramSig}): ${returnType} {\n  return stmtFindBy${pascalIdxName}.all(${argList}) as ${returnType};\n}`;

    ops.push({
      id: `auto-index-${tableName}-${rawIdxName}-${i}`,
      name: fnName,
      kind: "fetchByIndex",
      indexName: rawIdxName,
      description: `Fetch ${tableName} records by ${colList.join(", ")}`,
      signature: `${fnName}(${paramList.map((p) => `${p.name}${p.required === false ? "?" : ""}: ${p.type}`).join(", ")}): ${returnType}`,
      params: paramList,
      returnType: returnType,
      pagination: isUnique
        ? undefined
        : {
            enabled: true,
            defaultLimit: 20,
            maxLimit: 100,
            mode: "offset",
          },
      logicMode: "natural_language",
      prompt: `Fetch records from ${tableName} table matching ${whereClause}.`,
      code: indexCode,
      enabled: true,
      isAutoGenerated: true,
    });
  });

  return ops;
}

